# This is a temporal file that will be deleted once merged in nightly.yaml

on:
  push:
name: macOS build
jobs:
  macos:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    name: "macOS (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install meson gtk4 gtksourceview5 desktop-file-utils pygobject3 libadwaita adwaita-icon-theme gettext imagemagick inkscape
    - name: Fix PYTHONPATH for blueprint-compiler
      run: echo "PYTHONPATH=$(brew --prefix)/lib/python3.12/site-packages:$PYTHONPATH" >> $GITHUB_ENV
    - name: Build macOS version
      run: build-aux/macos-build.sh devel
    - name: Build installer
      run: build-aux/macos-installer.sh
    - uses: actions/upload-artifact@v4
      name: Upload macOS version
      with:
        name: es.danirod.Cartero-${{ runner.os }}-${{ runner.arch }}
        path: build/Cartero-*.dmg
